name: Branches

on:
  push:
    branches:
      - '*'

jobs:
  test_branch:
    runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ./manuscripts_be
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.7.0
        bundler-cache: true # runs 'bundle install' and caches installe
    - name: Migrate Test Database
      run: rails db:migrate RAILS_ENV=test
    - name: Run tests
      run: bundle exec rspec