name: Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test_develop:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts


    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 3.0.0
        working-directory: ./manuscripts_be
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Tests
      working-directory: ./manuscripts_be
      run: bundle exec rspec
