name: Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test_development:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manuscripts_be
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 3.0.0
    - name: Install dependencies
      run: bundle install
    - name: Migrate Test Database
      run: rake db:migrate SINATRA_ENV=test
    - name: Run Tests 
      run: bundle exec rspec
